name: Test Path

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "tytydraco/LADB"
          ref: "main"

      - name: test
        run: |
          echo "APK_PATH=${{ env.GITHUB_WORKSPACE }}/app/build/outputs/apk/release" >> $GITHUB_ENV
          
      - name: Checkout code
        uses: actions/checkout@v4
      - name: echo env
        run: |
          echo ${{ env.APK_PATH }}
